/* Generated by tools/gen_icons.py -- do not edit by hand. */

#ifndef DASHBOARD_ICONS_H
#define DASHBOARD_ICONS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_IMG_DECLARE(icon_lightbulb_24);  /* 24x24 */
LV_IMG_DECLARE(icon_lamp_desk_24);  /* 24x24 */
LV_IMG_DECLARE(icon_fan_24);  /* 24x24 */
LV_IMG_DECLARE(icon_sprout_24);  /* 24x24 */
LV_IMG_DECLARE(icon_house_18);  /* 18x18 */
LV_IMG_DECLARE(icon_moon_18);  /* 18x18 */
LV_IMG_DECLARE(icon_log_out_18);  /* 18x18 */
LV_IMG_DECLARE(icon_power_18);  /* 18x18 */
LV_IMG_DECLARE(icon_house_20);  /* 20x20 */
LV_IMG_DECLARE(icon_cloud_20);  /* 20x20 */
LV_IMG_DECLARE(icon_rotate_ccw_clock_20);  /* 20x20 */
LV_IMG_DECLARE(icon_settings_20);  /* 20x20 */
LV_IMG_DECLARE(icon_sun_20);  /* 20x20 */
LV_IMG_DECLARE(icon_cloud_sun_20);  /* 20x20 */
LV_IMG_DECLARE(icon_cloud_rain_lucide_20);  /* 20x20 */
LV_IMG_DECLARE(icon_sun_medium_20);  /* 20x20 */
LV_IMG_DECLARE(icon_sun_12);  /* 12x12 */
LV_IMG_DECLARE(icon_sun_32);  /* 32x32 */
LV_IMG_DECLARE(icon_cloud_sun_32);  /* 32x32 */
LV_IMG_DECLARE(icon_cloud_32);  /* 32x32 */
LV_IMG_DECLARE(icon_cloud_rain_lucide_32);  /* 32x32 */
LV_IMG_DECLARE(icon_botanical_72);  /* 72x98 */

#ifdef __cplusplus
}
#endif

#endif /* DASHBOARD_ICONS_H */
